services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: praxis-backend
    environment:
      SERVER_PORT: 8080
      WEBSOCKET_ALLOWED_ORIGINS: http://localhost,http://localhost:80,http://localhost:5173
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY:-}
      SUPABASE_URL: ${SUPABASE_URL:-}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:-}
      JWT_SECRET: ${JWT_SECRET:-}
    ports:
      - "8080:8080"
    networks:
      - praxis-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: praxis-frontend
    ports:
      - "5173:80"
    networks:
      - praxis-network
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: praxis-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - praxis-network
    restart: unless-stopped

networks:
  praxis-network:
    driver: bridge
