version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: praxis-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praxis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - praxis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: praxis-backend
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/praxis?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - praxis-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: praxis-frontend
    ports:
      - "5173:80"
    networks:
      - praxis-network
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: praxis-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - praxis-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  praxis-network:
    driver: bridge
